### ISSUE TITLE
stdout stderr

### ISSUE THREAD

**Issue by smiano33** [luisiam/homebridge-cmdswitch2#1]
In line 154 of index.js I think the  stdout should be stderr. This is for the state_cmd to work. If you echo 0 or 1 into stdout it is a work around.

**Comment by luisiam** [comment]
I built that assuming most of the people will be using `grep` for state checking. Even if `grep` is not able to find any match, it won't return any error and it will return an empty stdout. That's why I am using stdout instead of stderr.
