### ISSUE TITLE
HomeBridge with API 2.0 can handle configurations in the HomeKit app.?

### ISSUE THREAD

**Issue by jsmeyers** [luisiam/homebridge-cmdswitch2#10]
I am missing something on the configuration. I haven't been able to access this feature in my Eve or Home apps.

**Comment by luisiam** [comment]
AFAIK, only Hesperus support on the fly configuration.

**Comment by jsmeyers** [comment]
outstanding, works awesome

Hesperus supports homebridge configuration. After pairing with Homebridge, you can go to settings (upper left gear icon) -> accessories and swipe from right to left on the Homebridge cell, there is a "config" button which allows you to configure the supported plugins.
