### ISSUE TITLE
Is there a way to send a dim command?

### ISSUE THREAD

**Issue by jthurston** [luisiam/homebridge-cmdswitch2#11]
I am using a command line project called CM15ADEMO that sends commands to my X10 modules which is working nicely with the Homebridge and the cmswitch2 plugin! I was wondering can I make a enhancement request to send a dim command?

**Comment by luisiam** [comment]
Do you mean the slider to control the brightness?

**Comment by jthurston** [comment]
Yes, or be able to use SIRI to set a light dim value...
homebridge-http seems to have the following:

"accessories": [ 
   {
   	"accessory": "Http",
   	"name": "Alfresco Lamp",
   	"switchHandling": "realtime",
   	"http_method": "GET",
   	"on_url":      "http://localhost/controller/1700/ON",
   	"off_url":     "http://localhost/controller/1700/OFF",
   	"status_url":  "http://localhost/status/100059",
   	"service": "Light",
   	"brightnessHandling": "yes",
   	"brightness_url":     "http://localhost/controller/1707/%b",
   	"brightnesslvl_url":  "http://localhost/status/100054",
   	"sendimmediately": "",
   	"username" : "",
   	"password" : ""					    
      } 
   ]

"Set Living Room Lamps brightness to 50%" would produce a command of "Command" 50%

**Comment by luisiam** [comment]
Technically speaking, it's possible. However, this plugin is implemented as a general switch in HomeKit. This requires changes in the service (switch to lightbulb) or adding extra characteristics, which is too specific for certain application and I don't plan to do that in this plugin. Thanks.

**Comment by jthurston** [comment]
Okay, thank you for looking at it.

**Comment by epheterson** [comment]
Not a bad idea, while this is substantial work for homebridge-cmdswitch2, it's trivial work for homebridge-http. I've filed https://github.com/rudders/homebridge-http/issues/66
