### ISSUE TITLE
Possibility to change switch type?

### ISSUE THREAD

**Issue by Tommrodrigues** [luisiam/homebridge-cmdswitch2#32]
Hey, 
I’ve got cmdswitch2 set up to control a number of appliances in my house and it’s working great! I’ve managed to control my garage from it which is great. Unfortunately, there is a slight aesthetic problem that inside the home app, I am unable to change the type to a Garage Door Opener and only have the option for switch, light and fan. I was wondering if there is a way to change the type of switch inside the config.json so that it would appear as a Garage Door Opener. I have tried using the cmdaccessory plugin which does have the option to change the type to a Garage Door Opener but I am unable to open or close the garage as it is constantly checking for status but I have no way of updating its status due to the fact it is controlled by RF.
Any help or advice would be much appreciated, thank you in advance,
Tom

**Comment by GatoPharaoh** [comment]
#21

**Comment by theend92** [comment]
Whats the different between a Switch and a Garage Door Opener in the Home app?
I can surely help

**Comment by Tommrodrigues** [comment]
Hi GatoPharaoh that would be really helpful if you could :) Thank you for your reply and I apologise for not replying sooner as I hadn't seen your message.

**Comment by GatoPharaoh** [comment]
Have you tried this plugin [here](https://github.com/apexad/homebridge-garagedoor-command)

**Comment by i3laze** [comment]
Actually, good issue.
I'm triggering a surveillance system state using the plugin. I'd love to get a Security icon instead of simple switch. 
Can these masquerading be done plugin-side as some new option?
Profiles could be Fan/Lights/Outlet/Security/Humidifier/Purifier, e.t.c.
